//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yurtlar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string PName { get; set; }
        public string PDesc { get; set; }
        public Nullable<double> PPrice { get; set; }
        public byte[] PImage { get; set; }
        public Nullable<int> PStatus { get; set; }
        public Nullable<int> PStock { get; set; }
        public string PKyk { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
